### ISSUE TITLE
请问一下，你们何时正式发布代码呢？

### ISSUE THREAD

**Issue by sufubao** [galaxy-qazzz/AdaAffordCode#2]

**Comment by wangyian-me** [comment]
这个就是正式发布的代码，是我们实验代码的clean版本，可能在删除冗余代码和参数，写script的时候有些纰漏请您见谅。如果您需要follow我们的工作，我们可以给您发送我们的实验代码。或者您在运行代码的时候遇到什么问题我们也很高兴为您解答。如果有需要请再联系我们。

**Comment by sufubao** [comment]
好的，我可能需要实验代码，这是我的邮箱：jyily.xx00@gmail.com，非常感谢。
