### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by sufubao** [galaxy-qazzz/AdaAffordCode#3]
Excuse me, could you write a README. md at your convenience?  I really do not know how to run this code.  Thanks.

**Comment by wangyian-me** [comment]
I will upload one before tomorrow.

**Comment by sufubao** [comment]
> 

hi, are you sure your train steps wrote in readme.md is complete? Would you please check it again? thank you.

**Comment by wangyian-me** [comment]
would you please add the wechat sent to your email？so we can discuss more detailedly about your issue？

**Comment by wangyian-me** [comment]
or can you detail the problem you have met with? Then it would be easier for me to understand what's going wrong.

**Comment by JYILY** [comment]
> or can you detail the problem you have met with? Then it would be easier for me to understand what's going wrong.

We decide to use other project. Thanks for your reply.
