### ISSUE TITLE
Are 10000 training epochs necessary? 

### ISSUE THREAD

**Issue by akira-l** [galaxy-qazzz/AdaAffordCode#4]
The training code for AAP sets 10000 training epochs. I implemented this in my device and found about 2 minutes per epoch. Does that mean I have to run for about six days to achieve an AAP model?

**Comment by wangyian-me** [comment]
It's not necessary. Actually, it's hard to say exactly how many epochs are needed. Normally, it only needs less than 100 epochs.

**Comment by wangyian-me** [comment]
You might want to see the curve to decide when to stop the training process (when it converge).

**Comment by wangyian-me** [comment]
2 minutes per epoch might be too fast? It might need more data to get better performance.

**Comment by akira-l** [comment]
got it, thank you

**Comment by wangyian-me** [comment]
Welcome! Please feel free to contact me if you need any help.

**Comment by JayKamat99** [comment]
Hi, Would it be possible to get access to the pre-trained models?
