### ISSUE TITLE
How to evaluate the overall pipeline. 

### ISSUE THREAD

**Issue by akira-l** [galaxy-qazzz/AdaAffordCode#6]
After all the traning steps, I got; 
AAP model (by train_AAP.py),  
AIP model (by train_AIP.py), 
AAP_aff model (by train_AAP_aff.py), 
AIP_aff model (by train_AIP_aff.py), 
n_secondAAP model, and n_secondAIP model (by iter_train.py'). 

So there are six different models (ignore the epochs) but run_eval.sh only use the first four models. 

How to organize all six models and pick up the best combinations in evaluation?

**Comment by akira-l** [comment]
BTW, what is the size of generated training data? 
The generated training data for pushing in my implementation are 1.3G. Are these enough for training?

**Comment by wangyian-me** [comment]
How many batches you got? I collected over 3000 batches (batchsize=32) for pushing in my implementation (haven't considered online training).

**Comment by wangyian-me** [comment]
But I think 500 batches should be enough to get an okay result in pushing. After all, it's really a time-consuming job to collect so much data.

**Comment by wangyian-me** [comment]
Currently, run_eval.sh the script to evaluate our performance before iterative training. To evaluate it after iterative training, change the dir in the scripts.

**Comment by wangyian-me** [comment]
for example, change `--AAP_dir ../logs/model_AAP_para` into `--AAP_dir ../logs/final_model_para`.

**Comment by akira-l** [comment]
Yeah, I see. I will try it again. Thanks for your reply.

**Comment by wangyian-me** [comment]
BTW, you might have to train the affordance after iter_train. (If it's too redundant, I can give you a code that evaluate our pipeline without using affordance network, which results basically the same.)

**Comment by akira-l** [comment]
Sure. Could you update this code to this repo? Or email (my email: liangyzh18@outlook.com) directly? 
Thanks!
